spring:
  datasource:
    url: jdbc:sqlserver://ALPHAONE\\SQLEXPRESS:55054;databaseName=FoodSpring;schema=FoodSpring;encrypt=true;trustServerCertificate=true;
    username: hakim
    password: hakim
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: FoodSpring
        format_sql: true
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8000